---

## OS settings
sys_open_ports: "{{ sys_open_ports_spm_all }} + {{ sys_open_ports_apigateway_all }} + {{ sys_open_ports_terracotta_client_healthcheck_callbacks }} + {{ sys_open_ports_apigatewaykibana_all }}"

## These ports should be added only if CLUSTERED terracotta and internaldatastore are also running on the gateway...which should be rare as it's not best practice
## {{ sys_open_ports_terracotta }} + {{ sys_open_ports_internaldatastore }}"

limits_user: "{{ webmethods_user }}"
limits_openfiles: "250000"
limits_processes: "20000"

sysctl_config:
  vm.max_map_count: "262144"
  fs.file-max: "{{ limits_openfiles }}"

################### post install settings

webmethods_product_list:
  - product_name: "apigateway"
    product_instance_name: "default"
    process_memory_min: 4096
    process_memory_max: 4096
    process_params: {}

# the ports to check right after the install
webmethods_postinstall_validation_ports:
  - 5555
  - 9072
  - 9999

# the final ports to check for a completely valid install (post install and configure)
webmethods_validation_ports:
  - 5555
  - 9072
  - 9999
  - 9405

# special longer timeout because it can take a while for portal to come up, especially on first initial run
webmethods_validation_ports_timeout: 600

################### install settings

## Product install
webmethods_install_products_descriptor_list:
  - target_install_dir: "{{ webmethods_install_dir }}"
    clean_repo_after_install: true
    installer: "{{ webmethods_install_common_product_installer_descriptor }}"
    script:
      bucket_path: "product_repo/webmethods/10.5/scripts/apigateway/APIGW105Install.script"
      local_path: "{{ webmethods_install_common_repo_dir }}/APIGW105Install.script"
      force_download: true
    binaries_image:
      bucket_path: "product_repo/webmethods/10.5/images/products/softwareag_105_apigateway_linux_x64.zip"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_apigateway_linux_x64.zip"
    licenses:
      - bucket_path: "customer_specifics/IRS/licenses/softwareag/0000563012_APIGatewayAdvanced104.xml"
        local_path: "{{ webmethods_install_common_repo_dir }}/0000563012_APIGatewayAdvanced104.xml"

## Patch installs
webmethods_install_patches_descriptor_list:
  - target_install_dir: "{{ webmethods_install_dir }}"
    sum_home_dir: "{{ webmethods_install_sum_dir }}"
    fixes_overinstall: false
    sum_selfupdate: false
    clean_repo_after_install: true
    script:
      bucket_path: "product_repo/webmethods/10.5/scripts/apigateway/APIGW105Update.script"
      local_path: "{{ webmethods_install_common_repo_dir }}/APIGW105Update.script"
    binaries_image:
      bucket_path: "product_repo/webmethods/10.5/images/fixes/apigateway/softwareag_105_apigateway_linux_x64_fixes_20201202.zip"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_apigateway_linux_x64_fixes_20201202.zip"
  - target_install_dir: "{{ webmethods_install_dir }}"
    sum_home_dir: "{{ webmethods_install_sum_dir }}"
    fixes_overinstall: false
    sum_selfupdate: false
    clean_repo_after_install: true
    script:
      bucket_path: "product_repo/webmethods/10.5/scripts/apigateway/softwareag_105_apigateway_linux_x64_HOTFIX_YAI-18829_1.script"
      local_path: "{{ webmethods_install_common_repo_dir }}/wm_sum_patching_hotfix1.script"
    binaries_image:
      bucket_path: "product_repo/webmethods/10.5/images/fixes/apigateway/softwareag_105_apigateway_linux_x64_HOTFIX_YAI-18829_1.zip"
      local_path: "{{ webmethods_install_common_repo_dir }}/wm_sum_patching_hotfix1_image.zip"

## product licenses to download and re-install in real path after the initial install
webmethods_install_product_license_descriptor_list:
  - bucket_path: "customer_specifics/IRS/licenses/softwareag/0000563012_APIGatewayAdvanced104.xml"
    local_path: "{{ webmethods_install_dir }}/IntegrationServer/config/licenseKey.xml"
    force_download: "false"
  - bucket_path: "customer_specifics/IRS/licenses/softwareag/TC Clustering/terracotta-license.key"
    local_path: "{{ webmethods_install_dir }}/common/conf/terracotta-license.key"
    force_download: "false"

########################################################