---

## OS settings
sys_open_ports: "{{ sys_open_ports_spm_all }} + {{ sys_open_ports_integrationserver_all }}"

limits_user: "{{ webmethods_user }}"
limits_openfiles: "250000"
limits_processes: "20000"

sysctl_config:
  vm.max_map_count: "262144"
  fs.file-max: "{{ limits_openfiles }}"

################### post install settings

webmethods_product_list:
  - product_name: "integrationserver"
    product_instance_name: "default"
    process_memory_min: 1024
    process_memory_max: 2048
    process_params: {}

# the ports to check right after the install
webmethods_postinstall_validation_ports:
  - 5555
  - 9999

# the final ports to check for a completely valid install (post install and configure)
webmethods_validation_ports: "{{ webmethods_postinstall_validation_ports }}"

# special longer timeout because it can take a while for portal to come up, especially on first initial run
webmethods_validation_ports_timeout: 600

################### install / patching descriptors

## Product install
webmethods_install_products_descriptor_list:
  - target_install_dir: "{{ webmethods_install_dir }}"
    clean_repo_after_install: true
    installer: "{{ webmethods_install_common_product_installer_descriptor }}"
    script:
      bucket_path: "product_repo/webmethods/10.5/scripts/wmdeployer/softwareag_105_cicdtools_linux_x64_install_deployer.script"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_cicdtools_linux_x64_install_deployer.script"
      force_download: true
    binaries_image:
      bucket_path: "product_repo/webmethods/10.5/images/products/softwareag_105_cicdtools_linux_x64.zip"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_cicdtools_linux_x64.zip"
      force_download: true
    licenses:
      - bucket_path: "customer_specifics/IRS/licenses/softwareag/0000563008_Integration_Server100.xml"
        local_path: "{{ webmethods_install_common_repo_dir }}/0000563008_Integration_Server100.xml"
        force_download: true
  - target_install_dir: "{{ webmethods_install_dir }}"
    clean_repo_after_install: true
    installer: "{{ webmethods_install_common_product_installer_descriptor }}"
    script:
      bucket_path: "product_repo/webmethods/10.5/scripts/abe/softwareag_105_linux_x64_INSTALL_ABE.script"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_linux_x64_INSTALL_ABE.script"
      force_download: true
    binaries_image:
      bucket_path: "product_repo/webmethods/10.5/images/products/softwareag_105_cicdtools_linux_x64.zip"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_cicdtools_linux_x64.zip"
      force_download: true
    licenses: []

## Patch installs
webmethods_install_patches_descriptor_list:
  - target_install_dir: "{{ webmethods_install_dir }}"
    sum_home_dir: "{{ webmethods_install_sum_dir }}"
    fixes_overinstall: false
    sum_selfupdate: false
    clean_repo_after_install: true
    script:
      bucket_path: "product_repo/webmethods/10.5/scripts/wmdeployer/softwareag_105_cicdtools_linux_x64_fixes_20201201_deployer.script"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_cicdtools_linux_x64_fixes_20201201_deployer.script"
      force_download: true
    binaries_image:
      bucket_path: "product_repo/webmethods/10.5/images/fixes/cicdtools/softwareag_105_cicdtools_linux_x64_fixes_20201201.zip"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_cicdtools_linux_x64_fixes_20201201.zip"
      force_download: true
  - target_install_dir: "{{ webmethods_install_dir }}"
    sum_home_dir: "{{ webmethods_install_sum_dir }}"
    fixes_overinstall: false
    sum_selfupdate: false
    clean_repo_after_install: true
    script:
      bucket_path: "product_repo/webmethods/10.5/scripts/abe/softwareag_105_linux_x64_FIXES_WITH_INFRA.script"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_linux_x64_FIXES_WITH_INFRA.script"
      force_download: true
    binaries_image:
      bucket_path: "product_repo/webmethods/10.5/images/fixes/cicdtools/softwareag_105_cicdtools_linux_x64_fixes_20201201.zip"
      local_path: "{{ webmethods_install_common_repo_dir }}/softwareag_105_cicdtools_linux_x64_fixes_20201201.zip"
      force_download: true

## product licenses to download and re-install in real path after the initial install
webmethods_install_product_license_descriptor_list:
  - bucket_path: "customer_specifics/IRS/licenses/softwareag/0000563008_Integration_Server100.xml"
    local_path: "{{ webmethods_install_dir }}/IntegrationServer/config/licenseKey.xml"
    force_download: "false"

########################################################